### ISSUE TITLE
How to support HTML meta-tags like opengraph?

### ISSUE THREAD

**Issue by ErikMichelson** [codimd/react-client#104]
**What is your question?**
While using react as a frontend alone without server-side rendering, we can't include meta tags (like opengraph protocol data) into the page. Not only that we break an existing feature with this, but also link previews of CodiMD pads e.g. in messengers wouldn't look as good as in 1.6 anymore.

How can we avoid this problem if at all?

**Comment by mrdrogdrog** [comment]
We can add the basic meta tags (like icon and title) to the index.html. (See #56)
But I think you're talking about tags like the og:description, right?

We could drop that feature or use a react server side render server.

**Comment by DerMolly** [comment]
Would a react server-side render Server work with the express backend? And do we really want to go back to server-side rendering?

**Comment by ccoenen** [comment]
Yes, something _must_ be rendered serverside in my opinion. When you go to "https://example.com/demopage1" it should display at least the plain text of the document to a browser with no JavaScript at all.

**Comment by mrdrogdrog** [comment]
IMHO I wouldn't support deactivated javascript. The whole purpose of CodiMD ist interactivity.

**Comment by mrdrogdrog** [comment]
Yes, server-side rendering is compatible with express.

**Comment by ccoenen** [comment]
It is also a place where documentation lives that you might just want to take a look at. Or you might want to have indexed by a search engine. Having a basic representation and enhancing that with interactivity (i.e. normal use of CodiMD) is a very established standard practice in web development.

**Comment by SISheogorath** [comment]
> We could drop that feature

Just to make one thing sure: We can not drop this. This is eactly the reason why using Gitlab for anything else than private repositories is entirely broken. It doesn't do any SSR and that breaks SEO completely. Search for an project that is hosted on GitLab. You'll find the oddest results such as issue pages, commits, tons of third-party content but not the project page simply due to that.

And sharing a note should provide a proper link preview with a description and an icon, as well as the title of the document. This is essential. We don't have meaningful link names and therefore people should be able to use link previews to get an idea of what document they are going to open. If this is not working, that's a major road blocker.

**Comment by davidmehren** [comment]
For the record: We currently *don't* have any note content without JS.
Only the `meta` tags, but including/keeping them is a backend issue.
So we can probably close this here and just keep 'keeping the tags' in mind when marrying the new frontend and the backend.

**Comment by mrdrogdrog** [comment]
We could implement a simple server side rendering, that takes the react app's index.html as a template add some additional content like og tags and an offline preview.

But I agree with @davidmehren . This is an issue for the later development.
