### ISSUE TITLE
Show local and remote history

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#119]
**Is your feature request related to a problem? Please describe.**
In version 1.6. you can only see your local history or the remote history of notes.
If you're not logged in, then the history is shown from the local storage. If you're logged in, then you can only see your server history.
But sometimes it's necessary to see your local history while you're logged in, because you edited a note anonymously.

**Describe the solution you'd like**
Show the local history, too if you're logged in. (Maybe with a toggle button in the history toolbar?)
If a note is in both histories, then show only one.

**Describe alternatives you've considered**
You could always log out, find the note and log in again, but that's laborious.

**Additional context**
This issue doesn't deal with things like history migration, when to clear the local history or other writing actions! It's just the possibiliy to see BOTH histories.

**Comment by DerMolly** [comment]
I was just thinking about how to do that.
Currently the History Card and Row take an entry consisting of `id`, `title`, `lastVisited`, `tags` and `pinned`, but we would need to distinguish between a local and a remote entry.
Currently we only give on array of entries to the components. I propose to give to arrays one for local and one for remote entries and combine them in `HistoryContent`. My thought was that we could extend the HistoryEntry with `storage` field in there, so this field would be UI only. This approach  is especially nice, since we keep the two entry array separated and can easily move entries from one to the other.
What do you think?

**Comment by mrdrogdrog** [comment]
Currently the history component gets the history from the local storage, sends it through `sortAndFilterEntries` and sends the output to `HistoryContent`. I would keep that in the history component, because its just another filter.
