### ISSUE TITLE
New note permission screen

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#120]
**Which part of the project should be enhanced?**
The permission selection in the note editor.

**Is your enhancement request related to a problem? Please describe.**
In version 1.6 you can only choose one of these permission presets:
  - Freely - Anyone can edit
  - Editable - Signed-in people can edit
  - Limited - Signed-in people can edit (forbid guests)
  - Locked - Only owner can edit
  - Protected - Only owner can edit (forbid guests)
  - Private - Only owner can view & edit

For the most cases this is enough, but sometimes you need more precise settings like:
"I want everyone to view only, but user X and Y can write".

**Describe the solution you'd like**
I would keep the simple presets, but would also add an advanced mode, that allows the more precise settings. Maybe we could combine both. Like with a list of every logged in user, that every visited this doc and a pseudo user "guest". Next to every user you see a dropdown menu.

**Describe alternatives you've considered**
Using the simple presets and suffer.

**Additional context**
This issue is only for creating the UI (and maybe an API spec for the backend team).

**Comment by ErikMichelson** [comment]
Just for reference the similar PR in the server repo: codimd/server#322

**Comment by ccoenen** [comment]
I am opposed to "list of every user who visited that doc". This is a privacy concern.

This way you could go to - for example - `/features`, a page people likely visited at some point, and get a list of all users. (and that's just one scenario).

Also, I do not think this kind of fundamental change belongs in this repository but in codimd/server.

**Comment by mrdrogdrog** [comment]
Yes, it belongs here, because this issue is for the UI.

**Comment by mrdrogdrog** [comment]
Well the privacy concern argument is valid. As stated in codimd/server#322 we could use a search instead.

**Comment by ErikMichelson** [comment]
I would say the first step is to split the permissions into readable-by and writeable-by with just the settings "only me", "signed-in", "everyone".
We should then focus on a rework of the user system (e.g. multiple sign-in options for the same user account; unique user-names; ...). And after reworking that, we could implement the user-specific permissions.
An idea for that would be that each user may define in its profile, whether it wants to show up in a permission-search or not.

**Comment by mrdrogdrog** [comment]
I think the privacy concerns are not about if someone wants to be found in the search. They are about "list everyone who every opened this pad". And I'm okay with not doing that and implement a search instead.

**Comment by SISheogorath** [comment]
As stated in https://github.com/codimd/server/pull/322 I don't think it's a good idea to split permissions into "view" and "edit" because it creates more and even worse invalid states. Those have to be validated in both, backend and frontend. Yes, it would be great to simplify them, but I think we should way for that until we rework the entire permission system and not go for a half-backed intermediate version.

We have June now and looking at our first ETA for 2.0 which was around August, I don't think it's a good idea to get this started yet. Let's marry Frontend and Backend first, then make sure they work together properly and if that's the case, we should further extend the changeset and by that reworking permissions properly.

**Comment by DerMolly** [comment]
I closed this in favor of #424 as there are not current plans in that issue
