### ISSUE TITLE
Switch from cookies to local storage for the session id

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#121]
**Which part of the project should be enhanced?**
The session storage

**Is your enhancement request related to a problem? Please describe.**
After your log in, you'll get a session id. CodiMD 1.6 stored this id in a cookie. This is fine in 1.6, because the HTML is rendered server side and forms (e.g. for password change) get a CSRF-Token.

**Describe the solution you'd like**
To prevent CSRF, we shouldn't store the session id in a cookie. We could use the local storage or session storage, because then the browser won't send the session id automatically with every request.
We need some cooperation from the @codimd/developers team here. It would be much easier for us to send the session id in the http-header `authorization`.

**Describe alternatives you've considered**
There is no smoother alternative if you want to protect a REST-API from CSRF.

**Additional context**
@codimd/developers , if you plan switching to JWT, this would be the perfect time to tell us :yum:

**Comment by SISheogorath** [comment]
OWASP has a quite simple opinion about that:

> "Do not store session identifiers in local storage as the data is always accessible by JavaScript. Cookies can mitigate this risk using the httpOnly flag."

https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#local-storage

And the solution for CSRF is also not far:
https://github.com/expressjs/csurf

Also recommended by:
https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#javascript-guidance-for-auto-inclusion-of-csrf-tokens-as-an-ajax-request-header

**Comment by mrdrogdrog** [comment]
HttpOnly doesn't prevent CSRF, because we don't read the value from the cookie in js but the session is still sent with the request.

**Comment by mrdrogdrog** [comment]
A CSRF Middleware doesn't solve the issue. How do you want to get the token? Via an api call? And how do you want to verify the api call? Via cookie? And how do you want to prevent an xss on this endpoint?

**Comment by SISheogorath** [comment]
I'm not sure what you mean here. The httpOnly option does solve the question whether or not we should store session secrets in JS-available me storage.

Which means, we have to solve the remaining CSRF problem and here a CSRF middleware is exactly the solution.

Am I missing something? What would you need the auth data for?

**Comment by ErikMichelson** [comment]
The CSRF-middleware works good for server-side rendering of forms. The react-client on the other hand doesn't use server-side rendering for the forms, but instead relies on a REST API. Such an API should be stateless, but by relying on cookie data, we're adding a state into it.

**Comment by SISheogorath** [comment]
While I agree that this would be needed for a fully restful API, technically speaking we aren't going to achieve this anyway due to the fact that we have stateful websockets.

And in this case I definitely prefer an HTTPonly cookie over a JWT stored in local storage as we have a history with rather unpleasing XSS attacks. We are a an application that works with user generated content, we allow external requests via CSP and therefore I consider putting user session data into insecure storage a really bad idea. Especially since it doesn't solve any problem besides "it would be nice from a developer perspective"

**Comment by SISheogorath** [comment]
And as csurf suggests, providing the CSRF token as part of the serving GET request should solve the issue of using server-side rendering to embed it.

https://github.com/expressjs/csurf/blob/master/README.md#single-page-application-spa

**Comment by mrdrogdrog** [comment]
We have no serving get request. We don't do server side rendering of anything. The form that changes the user password is built by the react app. The only thing the app does is sending a request to the "change the user's password" endpoint.

That's why the server can't embed a CSRF-Token into anything except an API call.
But that wouldn't help. Because any XSS script can ask the endpoint to change the password or can request an CSRF-Token. And it would work, because the browser would send the session-cookie automatically.

A httponly-cookie wouldn't help either, because I don't have to read the session id to abuse it.

**Comment by SISheogorath** [comment]
Please read the OWASP document above. The reason to use httpOnly cookies is NOT that CSRF can't happen with it, but that session hijacking is much much harder.

(With local storage all you need is a XSS attack in a document that takes the local storage urlencodes it and creates a IMG tag to extract session tokens. This is horribly insecure in a application like CodiMD that is heavily built on user generated content that is rendered to HTML.

And as we already talked about in #104 the page is basically required to be served by the CodiMD server back end in order to function properly. That means we can easily attach a cookie to the served web application. That solves all three problems, the XSS vulnerability risk, the CSRF token problem and user authentication would be protected as well.

Also JWTs itself don't really solve the CSRF issue completely because you still want to protect `/register` and `/login` endpoint.

Also, just to prevent misunderstandings, the cookie csurf sets is intended to be read by the application from cookie storage and the submitted as own header as part of requests.

This cookie would simply be attached via the static webserver express provides us with that will serve the frontend code anyway.

**Comment by ErikMichelson** [comment]
The csurf token that will be supplied via cookie is only valid for one API request, isn't it?
If so, how to handle multiple password changes in one session? The react-app won't hard reload during a session.

**Comment by SISheogorath** [comment]
Also not a new problem:

https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#token-based-mitigation

> "CSRF tokens should be generated on the server-side. They can be generated once per user session or for each request. Per-request tokens are more secure than per-session tokens as the time range for an attacker to exploit the stolen tokens is minimal. However, this may result in usability concerns. For example, the "Back" button browser capability is often hindered as the previous page may contain a token that is no longer valid."

And while our concern is not the back button, it's still to use CSRF on multiple requests which is basically the same thing.

**Comment by mrdrogdrog** [comment]
Okay. Let's take a step back.
First of all: I'm sorry if my posts sounded aggressive. That wasn't my intention.
I reread the thread and see where some confusion could have come from:
- I already had in mind, that we could prepare CodiMD to run on different domains for backend and Frontend.
- I have confused which domain a cookie is used on. (The one that starts the request or the one that actually processes it)

If we assume that CodiMD backend and frontend run on different domains, then we don't need CSRF protection, because then that's what we're doing.

But if I remember correctly we agreed, that our first goal for 2.0 is to provide CodiMD under one domain.
So we need some kind of CSRF.

I have some unfinished proposals in mind for a workflow, that would make everybody happy, but I think thats a problem for the future.  If you're interested I can elaborate them somewhere else.

This issue deals with the change from cookies to local storage and I agree, that we shouldn't do that now.
