### ISSUE TITLE
Add Sync functionality to history entries

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#157]
**Which part of the project should be enhanced?**
The history page

**Describe the solution you'd like**
It should be possible to easily move a local entry to the database, maybe via the `…` menu planned in #79. It could be also possible to do the reverse, but I'm not sure if that is necessary...

**Comment by DerMolly** [comment]
Can anyone think of a good reason to move history entries from the server to the local storage?

**Comment by SISheogorath** [comment]
Given we want to go down the service-worker road that might be a reason. Otherwise, nope.

**Comment by HerHde** [comment]
IMO we should try to keep a complete (merged) history on the server side (as a Single Source of Truth:tm:)

- LocalStorage is not synced between a user's browsers (e.g. my Firefox desktop and my Firefox Mobile, even when logged into FF sync)
- It's tedious to click a handful of entries you want to sync (and to remember to do so, if you're using a private session etc eg.)
- for the offline client topic we should rather consider to use a library which handles the local/online sync stuff for more than just the history like [RxDB](https://github.com/pubkey/rxdb), to just call out one example
- I personally don't think it's a really popular use case to hold some history entries exclusively locally

Let's get this discussion going :wink:

**Comment by HerHde** [comment]
> LocalStorage should be avoided because it is synchronous and will block the main thread. It is limited to about 5MB and can contain only strings. **LocalStorage is not accessible from web workers or service workers.**
> -- https://web.dev/storage-for-the-web/

**Comment by mrdrogdrog** [comment]
@HerHde, we don't want to change the old behaviour. We still want to save and pull the history of a logged in user to and from the server.

**Comment by mrdrogdrog** [comment]
The local storage contains only anonymously visited notes.
The remote storage contains only notes that you visited while logged in.
We were just wondering if it could be handy to move/copy a history entry to the local history, so you can still find and visit it if you're logged out.

**Comment by mrdrogdrog** [comment]
Don't confuse this with the #103, where we want to implement a full synchronisation of notes, including their content.

**Comment by DerMolly** [comment]
An interesting point made in a discussion with @HerHde and @ErikMichelson: Do we really need to uploads notes one at a time or is the most wanted (possible only) scenario just push everything to the server?

**Comment by mrdrogdrog** [comment]
Why not both?

**Comment by SISheogorath** [comment]
Are we talking about notes or note history entries? History entires should be an array, as they are already. Notes should be one at the time.

**Comment by mrdrogdrog** [comment]
I would implement both. Import all via toolbar or import via the cards context menu

**Comment by ErikMichelson** [comment]
I just thought about our new recent notes history ideas again. Just to summarize the current (1.6) situation: Logged-in users have their remote history fetched from the server, anonymous users have their local browser history.

I asked some users about our new ideas and most of them didn't even know exactly that there's the remote history and the local history and that they may differ. I don't think that click-to-sync-buttons make the things more clear.

We should make the interface for our users (especially new ones) as easy to understand as possible. Therefore I disagree with ideas like 'sync single history entries to server'. As we intend to have some kind of offline support in the future, our note history should be designed properly now to avoid double work in the future.

To support offline situations the whole note history of an user should be stored locally. This means that we copy the whole remote history from the server to the local storage for logged-in users when accessing the history-page. Additionally we present them one[^1] "upload to server"-button if their local history contains non-online stored entries.

I know this could become problematic because an user might expect that all its locally stored data will be removed with the logout action. Therefore I suggest to add another field[^2] `origin` to history-entries which could either be `remote` or `local`. In the logout action we remove all entries from the local storage that are tagged with `remote`.

Another thing I want to mention are the new 'local' vs 'remote' icons on history entries. I know what they mean and why they're there, but as one person I asked pointed out these icons could be misunderstood as "this note is available locally" vs "this note just resides in the cloud". This could be come worse if we really decide to allow offline note-creation and note-viewing in the future. To be honest I'm still a bit unsure about how to present the state of the history to the user without overwhelming them.

[^1]: one in total, not one per entry
[^2]: a JSON-field, not necessary visible

Related: #103 #41 (#174)

**Comment by mrdrogdrog** [comment]
TBH: Can't we discuss that later? For version 2.0 we should focus on implementing the state from 1.6. An extra upload functionality (except just opening the note) is a new feature.

**Comment by ErikMichelson** [comment]
I don't think so. There's already some work in progress (#171) that includes parts of the behaviour. Most of the 1.6 features of the note history are already implemented, but if we postpone every decision and discussion, we might end up with changes that can't be done easily in a 2.1 or later, because we would need to break the API again as we've just recreated the 1.6 models with 2.0.

**Comment by mrdrogdrog** [comment]
A new api endpoint is no breaking change. I don't see where you need to alter the existing api to implement a call that adds a history entry.

**Comment by mrdrogdrog** [comment]
Okay. Let's take a step back and summarize.

What we want to do is NOT implementing some kind of offline-storage of notes.
It's ONLY about the history of recent notes. We want to have an API call that adds an note id to the users remote history. The server does this already, if you visit the note. So actually there is no change of behavior.

**Comment by mrdrogdrog** [comment]
In the old behavior the note won't be deleted from the local storage history so I would just keep that. 

If a note is in both histories, I would show only the entry from the remote history.

That's close enough to the old behaviour AND we can have a button.

Is there any other point?

**Comment by ErikMichelson** [comment]
Response schemata are part of the API spec, aren't they?
If so, it's just more than adding endpoints. I never talked about storing note contents in the comments above, I'm aware that we're probably not going to implement offline features in 2.0, but I want to mention that we shouldn't write a "new 1.6" but future-proof code and that implies discussion in beforehand.

**Comment by mrdrogdrog** [comment]
Yes, but we don't need to alter the response schema for this feature.

**Comment by ErikMichelson** [comment]
You're right with that regarding the API response.

**Comment by DerMolly** [comment]
Since the upload all local entries functionality is already implemented, the question is if we want to implement a single entry upload function. As far as I can see the answer seems to be no. So I'll suggest closing this issue...
