### ISSUE TITLE
Make the placeholder in the editor translateable / configurable

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#188]
**Which part of the project should be enhanced?**
the markdown editor

**Describe the solution you'd like**
The placeholder (before anything was typed) should be translateable and optionally configurable.
So either a default text chosen by us is shown (translated in the language the user chose) or the content of a markdown file from the backend is shown.

**Comment by SISheogorath** [comment]
To be honest, I don't see a need for it to be configurable. Especially when we translate it.

It's a placeholder that disappears on typing the first character, I see no situation where it would need to be replaced where a template (either default or something we add with 2.X in form of a template selection) wouldn't be better suited for the content of this.

Let's keep configuration options minimal and expend them when they are really needed.

But I'm definitely in for translating it 🚀

**Comment by DerMolly** [comment]
People asked for that at least twice, that's why I put it in the issue.

**Comment by SISheogorath** [comment]
@DerMolly if you are referring to https://github.com/codimd/server/issues/337 I talked with sunjam and iirc their goal was to use CodiMD more like a framework rather than an own application. I don't think its our goal to become a generic editor framework. Unless it has to be variable, we should try to hardcode as many things as possible. Because changing something hardcoded is easy, changing something generic is hard. And if people need adjustments there, there is still the possibility to modify the code and compile the frontend themselves.

**Comment by DerMolly** [comment]
I guess than we'll only translate them
