### ISSUE TITLE
Add info banner

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#189]
**Which part of the project should be enhanced?**
The top of the page

**Describe the solution you'd like**
The admin should have the possibility to add a banner at the top of the client to inform the users about stuff.

**Comment by ErikMichelson** [comment]
I'm getting a bit unsure about the banner now. What type of messages are intended to be displayed?

On the one hand it could be for static information like "This is a demo instance, running beta code - be careful!". In that case an administrator could set the text via an additional config option in the backend config[1]. But in this case it's unclear to me why a user should be able to dismiss the message.

On the other hand it could be used for a message of the day like "This instance is offline for maintenance tomorrow 6-8pm". In that case it wouldn't make any sense to load the message from the config because that would always require a restart of the server[2]. Instead, we probably would need new API-endpoints for setting and getting the message, including a differentiation between administrator users and normal users. Although that sounds better in first place, the (backend) code changes probably aren't worth it.

[1]: And that's against the goal to reduce the amount of config properties.
[2]: Or are there any thoughts to include hot-reloading of the config without a restart in 2.0?

**Comment by DerMolly** [comment]
I think the banner message could be used for both.

It should always be dismissable by the user because that's screen estate we prevent the user from using.

Static messages like 'this is a demo instance' are useful for demo.codimd.org and beyond, but I think the real kicker will be the ability to tell people who are using an instance of CodiMD that there will be a down time or something. Even if you would need to quickly restart the server.

**Comment by SISheogorath** [comment]
Implementation idea:

The backend detects if there is a file (e.g. `banner.md`) exists that will be rendered (like our current impress and terms). If it exists, we take the title of this document and ship it as part of the instance config to the frontend.

The frontend which simply displays the title of the note as banner and a links to the banner note.

This feature was explicitly requested by some institutes running CodiMD which want to hint to a restart of a codimd instance. Therefore a config change is not really an option.

**Comment by mrdrogdrog** [comment]
the first part could be implemented now. the second part can be implemented as soon as we have the markdown rendering component to realize a read only view

**Comment by ErikMichelson** [comment]
With the implementation idea above we could use the last change time of the `banner.md` file as an id for the banner and won't need to store the whole banner text in the localStorage (for the dismissing record) by the way.

**Comment by DerMolly** [comment]
What should the backend sent to the client in this case?

This:
```
…
"bannerText": <title of the banner.md file>
"bannerTimestamp": <unixtimestamp of the last change to the banner.md file>
…
```

The actual content would come through the regular note process would it not?

**Comment by ErikMichelson** [comment]
That looks exactly as I had it in my mind.

**Comment by mrdrogdrog** [comment]
well. we could implement this without any backend integration

**Comment by DerMolly** [comment]
Should clicking the banner text to go to the note dismiss the banner, too? Or should that be done explicitly via the x Button?

**Comment by ErikMichelson** [comment]
Just asking: Is there any intention to support non-dismissable banners?

**Comment by ErikMichelson** [comment]
But in general I would say that if a user does not explicitly close the banner, the banner should stay in place. Hiding the banner after clicking its link might lead to confusion for users that want to read it again; and the close icon is self-explanatory enough for those users that are annoyed by it.

**Comment by DerMolly** [comment]
@ErikMichelson Re: non-dismissable banners

I don't think so. That could be done in the future, but I think dismissable banners are good for now.

**Comment by SISheogorath** [comment]
I think a banner should always be dismissible. There is no reason why a banner that informs users about something should stay visible all the time.

Clicking on the banner should lead to a note that created the banner (e.g. `demo.codimd.org/s/banner` due to `banner.md` taking care of this) the dismissal should happen due to clicking the x.
