### ISSUE TITLE
Fullscreen image button

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#276]
**Describe the solution you'd like**
It would be nice if you could see images in full screen without leaving the doc. We could add a "fullscreen" button to the image frame component that opens an overlay.

**Describe alternatives you've considered**
Right-Click / open new image in tab

**Comment by SuperSandro2000** [comment]
This should probably only be shown for images with high enough resolution.

**Comment by SISheogorath** [comment]
Personally I never understood why people put those overlays out there. Usually it's more of a hassle to get back instead of just using the browser function if you went to see a picture in all detail.

I see the benefit, but my experience with this sort of features in other implementation tells me it's hard to get right and I'm not sure about the actual benefit.

**Comment by SuperSandro2000** [comment]
Most non tech people don't know that you can right click an image to view it on big.

**Comment by DerMolly** [comment]
I think this can be closed now, as it was implemented.
