### ISSUE TITLE
Rename 'pin' to 'favorite'

### ISSUE THREAD

**Issue by davidmehren** [codimd/react-client#330]
In the note history list, it is currently possible to 'pin' a note, which makes it stay at the top of the list.
I would like to rename this feature to 'favorite' as the concept of a 'list of favorites' is probably more common.

We could also tweak the UI a bit, e.g. with a bit of space between favorites and 'normal' notes.

**Comment by SISheogorath** [comment]
:thinking: I'm not sure why favourite would be preferred over "pin". Especially when I look how Mastodon basically had to implement "Bookmarks" because "Favourites" that were intended to be used like bookmarks, were understood wrong.

I could imagine that his happens with notes as well. To "pin" a note, on the other hand, seems rather clear to me. (We could also use the word "bookmark" if you insist on changing the term.) Generally speaking I think more and more tools use the word "pin" as we do. Mastodon has "pinned toots", GitHub has "pinned Repositories", Slack, Riot, … has "pinned messages" and Firefox has "pinned tabs". All of them have in common, that they stay at the top on an arbitrarily growing list of elements, which is exactly what pinned notes do in HedgeDoc.

**Comment by DerMolly** [comment]
As nobody else seems to be interested in changing pin to favorite and the 2nd part of the issue is covered by https://github.com/codimd/react-client/issues/158 I think this can be closed. If you think this discussions needs to be picked up again feel free to open it again.
