### ISSUE TITLE
View-Only-Mode

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#367]
Codimd had a "view-only" mode (`/s/`). We should reimplement this.

**Comment by ErikMichelson** [comment]
Just some notes: I just did some initial work for this in `feature/read-only-view`. While I created a new component to wrap the `MarkdownRenderWindow`, it looks as quite a lot of code from the `Editor` component needs to be reused (in order to parse the document title for example). Maybe we can abstract the `Editor` further to reduce code duplicity.

**Comment by ErikMichelson** [comment]
I'm waiting with this until we restructured the renderer/editor complex.
