### ISSUE TITLE
Add sequence diagram type

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#488]
This Issue is an sub-issue of #257 

**Describe the solution you'd like**
Re-add squence diagram type. This can be done via https://github.com/zfanta/react-sequence-diagram

**Comment by mrdrogdrog** [comment]
Please don't use https://github.com/zfanta/react-sequence-diagram. The repo wasn't updated since 2018 and the dependency is included as a file into the repo.

**Comment by mrdrogdrog** [comment]
js-sequence-diagram is unmaintained and it's architecture includes lot's of unnecessary dependencies like underscore.js. So I began to convert it into typescript and polish the code.
It's still horrible and untested.

@ccoenen had the idea to use mermaid instead as drop in replacement. I really like this idea, because:
- Mermaid ist maintained
- The syntax is very similar
- We have less dependencies (like snapsvg)
- We have to maintain less packages

The syntax is similar, but not the same.
Our proposal is, that we convert the sequence-diagram syntax to mermaid on the fly and show a warning, that says something like "The sequence-diagram renderer is deprecated. Please use mermaid instead (link to mermaid syntax). We automatically converted your code. To make it permanent click here".
The warning should only appear, if you have write access to the doc.

**Comment by mrdrogdrog** [comment]
@codimd/frontend , what do you think?

**Comment by DerMolly** [comment]
I think the last part should only appear if you have write access

**Comment by DerMolly** [comment]
Also I'm not sure if it would be easy to get an editor instance or something into the replacer (or should it be done in the markdown-it-plugin?). So maybe a simple always working click here to copy the translated code button would be a better solution?

**Comment by mrdrogdrog** [comment]
I wouldn't alter the code in the renderer.  Like in https://github.com/codimd/react-client/pull/283 I would just provide a callback and change the code somewhere else. 
It's going to be even easier after https://github.com/codimd/react-client/issues/496 was implemented.

**Comment by mrdrogdrog** [comment]
https://github.com/SAP/chevrotain seems to be the right lib for this.

**Comment by mrdrogdrog** [comment]
Okay I found out that the syntax is not only very similar. It's actually the same. So we can just use mermaid.
