### ISSUE TITLE
Namespace translations

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#81]
**Which part of the project should be enhanced?**
The translations files

**Is your enhancement request related to a problem? Please describe.**
Currently the translations files have NO structure. Every translation is put onto root level. You don't know for which component which translation is.

**Describe the solution you'd like**
 We should use namespaces to organize this more. Afaik you do this by creating sub objects in the translation files and use "x.y.z" syntax for the i18n key.

**Comment by ErikMichelson** [comment]
Is this syntax compatible with POEditor.com?

**Comment by DerMolly** [comment]
POEditor.com just want's a key value json file for the translations afaik
@SISheogorath

**Comment by mrdrogdrog** [comment]
I hope so.. because leveled translations are part of i18n

**Comment by mrdrogdrog** [comment]
```json
{
"a": {
  "b": "c"
}
}
```
was accepted by i18nnext if I use "a.b".

**Comment by mrdrogdrog** [comment]
TBH: If POEditor can't handle basic i18n features, then we should consider switching to another service.

**Comment by SISheogorath** [comment]
The good news is: Poeditor can handle more than just key-value for translation.

But I want to mention that I find it quite concerning with which lightness a "then let's switch to another platform" is outspoken. This should always be one of the last resorts because technical details are easy to workaround but bringing humans anywhere is hard. And moving translators from POeditor somewhere else will be a pain and most likely not work out. Please keep in mind that you are in the need of agreement from people. And people tend to be lazy and more likely drop something entirely before putting much more efforts into it.

And registering somewhere else or just sign up for notifications is such a big effort. We should try to not break everything with 2.0. We are already breaking more than enough.

On May 28, 2020 8:45:33 PM GMT+02:00, mrdrogdrog <notifications@github.com> wrote:
>TBH: If POEditor can't handle basic i18n features, then we should
>consider switching to another service.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/codimd/react-client/issues/81#issuecomment-635528318

-- 
Sheogorath

**Comment by mrdrogdrog** [comment]
It was meant as a absolut last resort.

But if POEditor can handle that.. then just let's do it. It will improve the code quality A LOT..

**Comment by SISheogorath** [comment]
Good to hear every carries that in mind :)

https://poeditor.com/localization/files/json <-- that's the format POEditor supports when it comes to json.

There are other formats like classic `.po` files that might work out better. The reason that poeditor was chosen back when it was chosen was the fact that is was the only place we could find that supported the very minimal key-value translation format that we use in 1.6.0 and provides a decent UI for people to work with. Yes, it's not the greatest and I would have preferred a FOSS solution, but at least at the time, it's not like there was an overwhelming number to chose from.

Hope that helps to figure out the structure :)

On May 29, 2020 9:16:55 AM GMT+02:00, mrdrogdrog <notifications@github.com> wrote:
>It was meant as a absolut last resort.
>
>But if POEditor can handle that.. then just let's do it. It will
>improve the code quality A LOT..
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/codimd/react-client/issues/81#issuecomment-635805230

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
